### ISSUE TITLE
Now-Playing Art Location

### ISSUE THREAD

**Issue by BlissWasTaken** [Comfy-Themes/Spicetify#131]
Is there any way to move the now-playing art back to the left? I know there used to be an option to switch between left and right but I can't find it anymore

**Comment by lupus0802** [comment]
The option was removed due to the new sidebar breaking the Now-playing art on the right feature. However, due to it not being rolled out for all users, it will be added again later (see the conversation on discord for more information).
For now, if you want your now-playing art on the left, you can enable the new sidebar (experimental) feature (then restart) and see how it looks. There's also a compact mode of that sidebar in Spotify Settings once you enabled it.

**Comment by ohitstom** [comment]
sorry I've been meaning to get around to it life's been busy recently.

**Comment by lupus0802** [comment]
> sorry I've been meaning to get around to it life's been busy recently.

No worries, there's a work around to it anyways :D
