### ISSUE TITLE
Lyrics are not shown

### ISSUE THREAD

**Issue by 0vs3rb4d0r** [Comfy-Themes/Spicetify#177]
**Environment**
Spotify para Windows (64 bits)
Spicetify v2.32.1
**Addons**
nothing 

It is quite simple when you activate this option you stop seeing the letters and the application does not show anything, the only option is to close and reopen, I hope you can solve it since your theme looks quite good, and I also really like how it looks. Bar at the top, I tried other configurations and came to the conclusion that the problem is there. I doubt it is my computer or client since otherwise everything worked, I realized that the version of spicetify in which your theme works is a previous to mine, and it may be because of that, but I still prefer to report the bug, thanks and very nice work

**Comment by ohitstom** [comment]
I will look into this as soon as possible!

**Comment by ohitstom** [comment]
the issue stems from Spotify trying to access the element we have moved so it can be removed when you open the lyrics page, since its in a different place it cant and crashes the main view.

cloning the element doesnt seem to help as the component creating it has memorized props so im unsure this issue can be fixed, i will keep looking into it but its unlikely.

the error in question:
![image](https://github.com/Comfy-Themes/Spicetify/assets/22730962/c7d74ec0-b101-49be-b111-dde6e9ddf9b2)

**Comment by ohitstom** [comment]
Spotify seems to have fixed this issue in version `1.2.32.997.g4c6498b6`
